name: UPM on npsjs.com
on:
  release:
    types: [created]
  workflow_dispatch:
env:
  # Dry-run on workflow_dispatch
  NPM_OPTS: ${{ github.event_name == 'workflow_dispatch' && '--dry-run' || '' }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish ${{ env.NPM_OPTS }}
      working-directory: Packages/com.github.asus4.texture-source
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
